cookietemple_version: '1.3.0 # <<COOKIETEMPLE_NO_BUMP>>'
domain: cli
language: python
project_slug: system-intelligence
project_slug_no_hyphen: system_intelligence
template_version: '2.0.0 # <<COOKIETEMPLE_NO_BUMP>>'
template_handle: cli-python
github_username: mlf-core
creator_github_username: Imipenem
is_github_repo: true
is_repo_private: false
is_github_orga: true
github_orga: mlf-core
full_name: Lukas Heumos
email: lukas.heumos@posteo.net
project_name: system-intelligence
project_short_description: Query your system for all hardware and software related
  information.
version: 2.0.1
license: Apache2.0
